-- Migration 002: Create indexes
-- All indexes for the base schema tables.

-- UP
CREATE INDEX IF NOT EXISTS idx_usage_company_metric ON usage_logs(company_id, metric);
CREATE INDEX IF NOT EXISTS idx_usage_timestamp ON usage_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_checkpoints_agent ON checkpoints(agent_id);
CREATE INDEX IF NOT EXISTS idx_incidents_company ON incidents(company_id);
CREATE INDEX IF NOT EXISTS idx_deployments_company ON deployment_history(company_id);
CREATE INDEX IF NOT EXISTS idx_deployments_status ON deployment_history(status);
CREATE INDEX IF NOT EXISTS idx_retry_logs_task ON retry_logs(task_id);
CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_company ON logs(company_id);
CREATE INDEX IF NOT EXISTS idx_logs_level ON logs(level);
CREATE INDEX IF NOT EXISTS idx_logs_source ON logs(source);
CREATE INDEX IF NOT EXISTS idx_budget_company ON budget_config(company_id);
CREATE INDEX IF NOT EXISTS idx_project_config_company ON project_config(company_id);
CREATE INDEX IF NOT EXISTS idx_forecasts_company ON workload_forecasts(company_id);
CREATE INDEX IF NOT EXISTS idx_forecasts_type ON workload_forecasts(forecast_type);
CREATE INDEX IF NOT EXISTS idx_forecasts_time ON workload_forecasts(time_bucket);
CREATE INDEX IF NOT EXISTS idx_agent_runs_agent ON agent_runs(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_runs_task ON agent_runs(task_id);
CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON agent_runs(status);
CREATE INDEX IF NOT EXISTS idx_agent_runs_start_time ON agent_runs(start_time);
CREATE INDEX IF NOT EXISTS idx_task_executions_task ON task_executions(task_id);
CREATE INDEX IF NOT EXISTS idx_task_executions_company ON task_executions(company_id);
CREATE INDEX IF NOT EXISTS idx_task_executions_status ON task_executions(status);
CREATE INDEX IF NOT EXISTS idx_agent_metrics_company ON agent_metrics(company_id);
CREATE INDEX IF NOT EXISTS idx_agent_metrics_agent ON agent_metrics(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_metrics_type ON agent_metrics(metric_type);
CREATE INDEX IF NOT EXISTS idx_agent_metrics_timestamp ON agent_metrics(timestamp);
CREATE INDEX IF NOT EXISTS idx_anomalies_company ON anomalies(company_id);
CREATE INDEX IF NOT EXISTS idx_anomalies_agent ON anomalies(agent_id);
CREATE INDEX IF NOT EXISTS idx_anomalies_severity ON anomalies(severity);
CREATE INDEX IF NOT EXISTS idx_anomalies_detected_at ON anomalies(detected_at);
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON metrics(timestamp);
CREATE INDEX IF NOT EXISTS idx_metrics_name ON metrics(metric_name);
CREATE INDEX IF NOT EXISTS idx_metrics_agent ON metrics(agent_id);
CREATE INDEX IF NOT EXISTS idx_metrics_company ON metrics(company_id);
CREATE INDEX IF NOT EXISTS idx_traces_trace_id ON traces(trace_id);
CREATE INDEX IF NOT EXISTS idx_traces_span_id ON traces(span_id);
CREATE INDEX IF NOT EXISTS idx_traces_parent_span_id ON traces(parent_span_id);
CREATE INDEX IF NOT EXISTS idx_traces_operation ON traces(operation);
CREATE INDEX IF NOT EXISTS idx_traces_timestamp ON traces(timestamp);

-- DOWN
DROP INDEX IF EXISTS idx_traces_timestamp;
DROP INDEX IF EXISTS idx_traces_operation;
DROP INDEX IF EXISTS idx_traces_parent_span_id;
DROP INDEX IF EXISTS idx_traces_span_id;
DROP INDEX IF EXISTS idx_traces_trace_id;
DROP INDEX IF EXISTS idx_metrics_company;
DROP INDEX IF EXISTS idx_metrics_agent;
DROP INDEX IF EXISTS idx_metrics_name;
DROP INDEX IF EXISTS idx_metrics_timestamp;
DROP INDEX IF EXISTS idx_anomalies_detected_at;
DROP INDEX IF EXISTS idx_anomalies_severity;
DROP INDEX IF EXISTS idx_anomalies_agent;
DROP INDEX IF EXISTS idx_anomalies_company;
DROP INDEX IF EXISTS idx_agent_metrics_timestamp;
DROP INDEX IF EXISTS idx_agent_metrics_type;
DROP INDEX IF EXISTS idx_agent_metrics_agent;
DROP INDEX IF EXISTS idx_agent_metrics_company;
DROP INDEX IF EXISTS idx_task_executions_status;
DROP INDEX IF EXISTS idx_task_executions_company;
DROP INDEX IF EXISTS idx_task_executions_task;
DROP INDEX IF EXISTS idx_agent_runs_start_time;
DROP INDEX IF EXISTS idx_agent_runs_status;
DROP INDEX IF EXISTS idx_agent_runs_task;
DROP INDEX IF EXISTS idx_agent_runs_agent;
DROP INDEX IF EXISTS idx_forecasts_time;
DROP INDEX IF EXISTS idx_forecasts_type;
DROP INDEX IF EXISTS idx_forecasts_company;
DROP INDEX IF EXISTS idx_project_config_company;
DROP INDEX IF EXISTS idx_budget_company;
DROP INDEX IF EXISTS idx_logs_source;
DROP INDEX IF EXISTS idx_logs_level;
DROP INDEX IF EXISTS idx_logs_company;
DROP INDEX IF EXISTS idx_logs_timestamp;
DROP INDEX IF EXISTS idx_retry_logs_task;
DROP INDEX IF EXISTS idx_deployments_status;
DROP INDEX IF EXISTS idx_deployments_company;
DROP INDEX IF EXISTS idx_incidents_company;
DROP INDEX IF EXISTS idx_checkpoints_agent;
DROP INDEX IF EXISTS idx_usage_timestamp;
DROP INDEX IF EXISTS idx_usage_company_metric;
